import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";


const josefin_Sans = Roboto({
  subsets: ["latin"],
  weight: ["400","600"],
})

export const metadata: Metadata = {
  title: "Görev Yönetim Sistemi",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        
      
      <body className={josefin_Sans.className}  suppressHydrationWarning={true}>
        {children}
      </body>
    </html>
  );
}
